baseURL = 'https://fotografia.mateusbernardo.xyz/'
languageCode = 'pt'
defaultContentLanguage = 'pt'
title = 'Mateus Bernardo'
theme = 'gallery'
timeZone= 'America/Sao_Paulo'
timeout = "120s"
defaultTheme = "dark"
description = "Example site for hugo-theme-gallery"
  [params.author]
    email = "mateusbernardo@protonmail.com"
    name = "Mateusb Bernardo"
  [params.socialIcons]
    email = "mailto:mateusbernardo@protonmail.com"

[outputs]
  home = ["HTML", "RSS"]
  page = ["HTML"]
  section = ["HTML"]

[imaging]
  quality = 100
  resampleFilter = "CatmullRom"
  [imaging.exif]
    disableDate = true
    disableLatLong = true
    includeFields = "ImageDescription|Orientation"

[menu]
  [[menu.footer]]
    name = "GitHub"
    url = "https://github.com/nicokaiser/hugo-theme-gallery/"
    weight = 3

[services]
  [services.rss]
    limit = 100
